PALETTE = {
    "background": "#0B0B0C",
    "bar": "#E0A458",
    "label": "#E0A458",
    "value": "#DEDDD4",
    "highlight": "#5FE3C4",
    "link": "#6BA8F5",
    "dots": "#37373A",
    "rule": "#26262A",
}

ROWS = [
    {"kind": "pair", "label": "Name", "value": "F. ANHAF DEV", "tone": "highlight"},
    {"kind": "pair", "label": "Username", "value": "anhafdev", "tone": "highlight"},
    {"kind": "pair", "label": "Role", "value": "Python Automation & Full-Stack Developer"},
    {"kind": "pair", "label": "Experience", "value": "3+ Years"},
    {"kind": "pair", "label": "Location", "value": "Bangladesh"},

    {"kind": "rule"},
    {"kind": "heading", "text": "Tech Stack"},
    {"kind": "pair", "label": "Languages", "value": "Python, JavaScript, SQL, HTML, CSS"},
    {"kind": "pair", "label": "Frameworks", "value": "FastAPI, Flask, aiogram,"},
    {"kind": "pair", "label": "", "value": "Playwright, React, Next.js"},
    {"kind": "pair", "label": "Databases", "value": "MySQL, MongoDB, PostgreSQL"},

    {"kind": "rule"},
    {"kind": "heading", "text": "Expertise"},
    {"kind": "bullet", "text": "REST API Development"},
    {"kind": "bullet", "text": "Full Stack Development"},
    {"kind": "bullet", "text": "Website Scraping"},
    {"kind": "bullet", "text": "Python Automation"},
    {"kind": "bullet", "text": "Crypto Payments System"},
    {"kind": "bullet", "text": "Telegram Bot Development"},
    {"kind": "bullet", "text": "Business Process Automation"},
    {"kind": "bullet", "text": "FastAPI / Flask Backend Development"},
    {"kind": "bullet", "text": "Security Implementation & Testing"},
    {"kind": "bullet", "text": "API Integration"},
    {"kind": "bullet", "text": "Server Deployment & Maintenance"},
    {"kind": "bullet", "text": "Performance Optimization"},
    {"kind": "bullet", "text": "Database Design & Management"},
    {"kind": "bullet", "text": "Workflow Automation"},

    {"kind": "rule"},
    {"kind": "heading", "text": "Contact"},
    {"kind": "pair", "label": "Website", "value": "https://anhaf.dev", "tone": "link"},
    {"kind": "pair", "label": "GitHub", "value": "https://github.com/anhafdev", "tone": "link"},
    {"kind": "pair", "label": "Email", "value": "contact@anhaf.dev", "tone": "link"},
]

LAYOUT = {
    "font_size": 17.0,
    "heading_size": 18.5,
    "line_height": 31.0,
    "bar_x": 26.0,
    "text_x": 52.0,
    "value_x": 300.0,
    "bullet_indent": 34.0,
    "top_padding": 34.0,
    "bottom_padding": 34.0,
    "width": 880.0,
    "rule_gap": 14.0,
    "word_delay": 0.042,
    "line_pause": 0.03,
}